"""
Authentication service.

IMPORTANT — hashing vs encryption
──────────────────────────────────
Passwords are HASHED, not encrypted. The difference matters:

  Encryption  →  reversible. You can recover the original value
                 with the right key. Bad for passwords because if
                 the key leaks, every password leaks too.

  Hashing     →  one-way. You cannot recover the original password
                 from the hash. To verify a login you hash the
                 attempt and compare the two hashes. bcrypt is
                 specifically designed for password hashing: it is
                 intentionally slow (to resist brute-force) and
                 embeds a random salt (so two identical passwords
                 produce different hashes, defeating rainbow tables).

The hash stored in Firestore looks like:
  $2b$12$eImiTXuWVxfM37uY4JANj.3gj4oqlCqy2TrMMM41TDnq9YRKw8Ka2

$2b = bcrypt algorithm
$12 = cost factor (number of hashing rounds as 2^12 = 4096)
The rest = 22-character salt + 31-character hash, concatenated.
"""

import bcrypt

from extensions import get_db


class AuthService:
    """
    Handles user registration and login against the Firestore 'users' collection.

    The 'users' collection is created automatically in Firestore the first time
    a guest registers. Each document in the collection represents one user and
    stores only two fields:

        username      (str)  — the name the guest chose, stored in lowercase
                               so 'Maria' and 'maria' are treated as the same user.
        password_hash (str)  — the bcrypt hash of their password. The original
                               password is never stored anywhere.

    The document ID is auto-generated by Firestore (same pattern as RSVPs).
    We query by the 'username' field rather than by document ID.
    """

    COLLECTION = 'users'

    @classmethod
    def _find_user(cls, username: str):
        """
        Search the 'users' collection for a document whose 'username' field
        matches the given value (case-insensitive, via lowercase normalisation).

        Firestore queries use .where() to filter documents server-side —
        only matching documents are transferred over the network, not the
        whole collection. .limit(1) tells Firestore to stop after the first
        match, making the query as cheap as possible.

        Args:
            username: The name to search for (will be lowercased before querying).

        Returns:
            The first matching DocumentSnapshot, or None if no user was found.
        """
        db = get_db()
        results = (
            db.collection(cls.COLLECTION)
            .where('username', '==', username.lower())
            .limit(1)
            .stream()
        )
        docs = list(results)
        return docs[0] if docs else None

    @classmethod
    def _hash_password(cls, password: str) -> str:
        """
        Hash a plain-text password with bcrypt and return the hash as a string.

        bcrypt.gensalt() generates a random 16-byte salt and encodes the cost
        factor into it. The salt is included in the final hash string, so you
        never need to store it separately — it will be re-read automatically
        during verification.

        bcrypt.hashpw() expects bytes, so we encode the password to UTF-8 first.
        The result is also bytes; we decode back to a plain str for storage in
        Firestore (Firestore does not accept raw bytes as field values).

        Args:
            password: The plain-text password entered by the user.

        Returns:
            A bcrypt hash string safe to store in the database.
        """
        salt = bcrypt.gensalt()
        hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), salt)
        return hashed_bytes.decode('utf-8')

    @classmethod
    def _verify_password(cls, password: str, stored_hash: str) -> bool:
        """
        Check whether a plain-text password matches a stored bcrypt hash.

        bcrypt.checkpw() extracts the salt from stored_hash, re-hashes the
        candidate password with that same salt, then compares the two hashes
        in constant time (preventing timing attacks). You never need to handle
        the salt yourself.

        Args:
            password: The plain-text password entered at login time.
            stored_hash: The bcrypt hash string retrieved from Firestore.

        Returns:
            True if the password matches the hash, False otherwise.
        """
        return bcrypt.checkpw(
            password.encode('utf-8'),
            stored_hash.encode('utf-8'),
        )

    @classmethod
    def register_or_login(cls, username: str, password: str) -> tuple[bool, str]:
        """
        The single entry point for the authentication flow.

        Because this is a wedding page with a limited guest list, we show only
        one form. The behaviour depends on whether the username already exists:

          Username NOT found in Firestore
            → Create a new user document with the hashed password.
            → Return (True, 'registered').

          Username found AND password matches
            → Return (True, 'logged_in').

          Username found BUT password is wrong
            → Return (False, 'wrong_password').

        The caller (routes/auth.py) decides what flash message to show and
        whether to set the session based on the returned tuple.

        Args:
            username: The name entered by the guest. Stored and compared
                      in lowercase so the form is case-insensitive.
            password: The plain-text password entered by the guest.

        Returns:
            A (success: bool, reason: str) tuple.
        """
        existing = cls._find_user(username)

        if existing is None:
            # First time this name is used — create the account.
            db = get_db()
            db.collection(cls.COLLECTION).add({
                'username': username.lower(),
                'password_hash': cls._hash_password(password),
            })
            return True, 'registered'

        # User exists — verify the password.
        user_data = existing.to_dict()
        if cls._verify_password(password, user_data['password_hash']):
            return True, 'logged_in'

        return False, 'wrong_password'
